In [ ]:
#풀이
def solution(url):
    return url.split('@')[0] + '@weniv.co.kr'

solution('user@wenive.co.kr')

'user@weniv.co.kr'

In [ ]:
# 변경된 문제의 해답
import re

def chagedomain(url):
    return url.split('@')[0] + '@weniv.co.kr'

# 콤마는 의도적으로 넣지 않은 것입니다.
findpattern = re.findall(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}",
                         "저의 이메일 주소는 kim123@gmail.com입니다."
                         "친구의 이메일 주소는 lee456@gmail.com입니다.")

for url in findpattern:
    print(chagedomain(url))

kim123@weniv.co.kr
lee456@weniv.co.kr


In [ ]:
# 출제 했던 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}", "user@weniv.co.kr", my_string)

'저의 이메일 주소는 user@weniv.co.kr입니다. 친구의 이메일 주소는 user@weniv.co.kr입니다.'

In [ ]:
# 변경된 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}", "@weniv.co.kr", my_string)

'저의 이메일 주소는 kim123@weniv.co.kr입니다. 친구의 이메일 주소는 lee456@weniv.co.kr입니다.'

In [ ]:
# # 코딩 인터뷰 완전분석
# 듣기
# 예제
# 무식하게 풀기
# 최적화
# 검토하기
# 구현하기
# 테스트
def solution(data):
    return

solution()

In [ ]:
def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    count_홀수 = []
    count_짝수 = []
    for i in 홀수:
        if i == True:
            count_홀수.append(i)
    for j in 짝수:
        if j ==  True:
            count_짝수.append(j)
    woaks = [len(count_짝수), len(count_홀수)]

    return woaks

solution([1, 2, 3, 4, 5])

[3, 2]

In [ ]:
def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    # print(홀수, 짝수)
    return [sum(짝수), sum(홀수)]

In [ ]:
def solution(data):
    count = 0
    for i in data:
        if i % 2 == 0:
            count += 1
    return [count, len(data)-count]

In [ ]:
def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1
    return answer

In [ ]:
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    갯수 = sum(짝수)
    return [갯수, len(data) - 갯수]

In [ ]:
def solution(array, height):
    answer = 0

    return answer

## 머쓱이

In [ ]:
array = [149, 180, 192, 170]
height = 167

In [ ]:
# 이렇게 언패킹 해서 사용할 수 있는 것들은 언패킹 해주세요.
# 가독성이 좋아집니다!
def solution(data):
    array, height = data
    pass

solution([[149, 180, 192, 170], 167])

In [ ]:
def solution(array, height):
    count = 0
    for i in array:
        if i > height:
            count += 1
    return count

In [ ]:
# filter는 len가 없습니다!
def solution(array, height):

    return len(list(filter(lambda x: x> height, array)))

solution([149, 180, 192, 170], 167)

# 왜? filter에는 len가 없나요?
# filter는 순회 돌기 전까지 실행이 되지않은 함수
# for와 같이 순회를 돌아야 각 원소 별로 접근해서
# 주문만 하고 아직 제조되지 않은 커피

3

In [ ]:
def solution(array, height):
    return sum(map(lambda x: x > height, array))

solution([149, 180, 192, 170], 167)

3

In [ ]:
def solution(array, height):
    return sum(map(lambda x: x > height, array))

solution([149, 180, 192, 170], 167)

3

In [ ]:
def solution(array, height):
    return sum(i > height for i in array)

solution([149, 180, 192, 170], 167)

3

# 숨어있는 숫자의 덧셈

In [ ]:
def solution(my_string):
    answer = 0
    return answer

In [ ]:
def solution(s):
    result = 0
    for i in s:
        if i.isdigit():
            result += int(i)
    return result
solution("aAb1B2cC34oOp")

10

In [ ]:
def solution(my_string):
    return sum(map(int,list(filter(str.isdigit, my_string))))

solution("aAb1B2cC34oOp")

10

In [ ]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return sum(map(lambda x: int(x) if x.isdigit() else False, my_string))

solution("aAb1B2cC34oOp")

10

In [ ]:
# r 는 raw 날것의 라는 뜻이 있어요.
# 실무에서 자주쓴는 용어입니다. raw != low(이 용어는 자주 사용하지 않습니다.)
# raw data를 전달해줘 => 가공하지 않은 순수 데이터를 달라는 얘기입니다.

r'hello\world' # \n 이스케이프 문자입니다.
print('hello\world') # 정규표현식에서 이스케이프

hello\world


In [ ]:
import re

re.findall(r'[0-9]','aAb1B2cC34oOp')

['1', '2', '3', '4']

In [ ]:
import re

def solution(s):
    return sum(map(int, re.findall(r'[0-9]', s)))

solution('aAb1B2cC34oOp')

10

In [ ]:
import re

def solution(s):
    return sum(map(int, (re.sub(r'[a-zA-Z]', '', s))))

solution('aAb1B2cC34oOp')

10

In [ ]:
def solution(cipher, code):
    answer = ''
    for i, in cipher:


    return answer

solution("dfjardstddetckdaccccdegk", 4)

SyntaxError: expected ':' (<ipython-input-37-c701348f341f>, line 3)

In [ ]:
def solution(cipher, code):
    return cipher[code-1::code]

solution("dfjardstddetckdaccccdegk", 4)

'attack'

In [ ]:
def solution(cipher, code):
    count = 1
    for i in cipher:
        if count == code:
            print(i)
            count = 0
        count += 1

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [ ]:
def solution(cipher, code):
    count = 1
    for i, j in enumerate(cipher, 1):
        if i % code == 0:
            print(j)

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [ ]:
# 이런 풀이는 권하지 않습니다.
def solution(cipher, code):
    result = ''
    for i in range(1, len(cipher) // code + 1):
        result += cipher[i * code - 1]
    print(result)

solution("dfjardstddetckdaccccdegk", 4)

attack


In [ ]:
s = 0
for i in range(1, 101):
    s += 1

n = 100
s = n * (n + 1) // 2
print(s)

5050


# 369 게임

In [ ]:
def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') + order.count('9')

In [ ]:
import re

def solution(order):
    order = str(order)
    return len(list(re.findall(r'[369]', 'order')))

In [ ]:
# 중복문자 제거

In [ ]:
list(set('people'))

['o', 'p', 'e', 'l']

In [ ]:
def solution(s):
    answer = ''
    for i in s:
        if i not in answer:
            answer += i
    return answer

solution('people')


'peol'

In [ ]:
def solution(my_string):
    return dict.fromkeys(my_string) # 딕셔너리는 키 중복이 안된다는 점을 이용!

solution('people')

{'p': None, 'e': None, 'o': None, 'l': None}

In [ ]:
def solution(my_string):
    return ''.join(dict.fromkeys(my_string))

solution('people')

'peol'

In [ ]:
''.join('hello', 'world', '!')
''.join('hello', 'world', '!')
''.join({'one' : 10, 'two': 20})

TypeError: str.join() takes exactly one argument (3 given)

In [ ]:
str.isdigit
dict.fromkeys('hello')
dict.fromkeys('abccba')

{'a': None, 'b': None, 'c': None}

# A로 B만들기

In [ ]:
def solution(before, after):
    s = ''
    for i in after:
        s = i + s
    if before == s:
        return 1
    else:
        return 0

solution('olleh','hello')

olleh


1

In [ ]:
def f(before, after):
    if len(before) <= 1:
        return before
    before = f(before[1:]) + before[0]
    if before == after:
        return 1
    else:
        return 0

f('olleh', 'hello')

# f('hello')      f('ello') + 'h' == 'olleh'
# f('ello')       f('llo') + 'e' == 'olle'
# f('llo')        f('lo') + 'l' == 'oll'
# f('lo')         f('o') + 'l' == 'ol'
# f('o')          'o'

TypeError: f() missing 1 required positional argument: 'after'

In [ ]:
def solution(before, after):
    if len(before) != len(after): # 예외 처리는 반드시
        return 0
    elif sorted(before) == sorted(after):
        return 1
    else:
        return 0


In [ ]:
def solution(before, after):

    for i in set(before):
        if before.count(i) != after.count(i):
            return 0
        else:
            return 1


solution('olleh','hello')

1

In [ ]:
import collections


# collections.Counter("olleh") == collections.Counter("hello")
# collections.Counter("olleh") == collections.Counter("hhhhhhhhhello")
collections.Counter("olleh")

Counter({'o': 1, 'l': 2, 'e': 1, 'h': 1})

In [ ]:
def solution(before, after):
    a = list(after)
    for i in before:
        if i in a:
            a.remove(i)
        else:
            return 0
    if a:
        return 0
    return 1

solution("olleh", "hello")

1

In [ ]:
# 회문

# 'hello' => 'elloh' => 'llohe'
# 'hello' => 'ohell' => 'lohel'
# collections.deque를 사용해서 풀면 쉽게 풀립니다.

# 문제1 'hello'를 앞뒤로 이동시켜 'llohe'를 만들 수 있나요?
# 'hellohello'

# 문제2 몇칸 이동했나요?
# 'hellohello'.index('llohe')

In [ ]:
## 저주의 숫자 3
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120871

SyntaxError: invalid syntax (<ipython-input-83-fdc65e8362e8>, line 2)

In [ ]:
# 십진수    3숫자마을
# 1         1
# 2         2
# 3         4
# 4         5
# 5         7
# 6         8
# 7         10
# 8         11
# 9         14
# 10        16

In [ ]:
# [True, True, False]...

In [ ]:
# filter('3이 들어간 숫자 없애기', filter('3의 배수 없애기', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

In [ ]:
list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(100)))[15-1]

25

In [ ]:
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(1,1000)))[num]



In [ ]:
solution = lambda n:[i for i in range(10000) if i % 3 != 0 and '3' not in str(i)][n-1]

In [ ]:
def solution(num):
    l = []
    for i in range(1000):
        if i % 3 != 0:
            l.append(i)
        elif '3' not in str(i):
            l.append(i)
    print(l)

solution(15)

[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 232, 233, 235, 2

In [ ]:
# 진료순서 정하기

In [ ]:
# emergency     result
# [3, 76, 24]   [3, 1, 2]

# emergency     result
# [3, 76, 24]   [3, 1, 2]

def solution(emergency):
    pass


solution([3, 76, 24] )

In [ ]:
emergency = [3, 76, 24]

sorted_emergency = sorted(emergency, reverse = True)
sorted_emergency

# 원하는 결과 값 [3, 1, 2]
[sorted_emergency.index(i) + 1 for i in emergency]

[3, 1, 2]

In [ ]:
data = ['제주', '경기', '전주'] # [1064]
data2 = {
    '제주': '064',
    '경기': '031',
    '전주': '063'
}

[data2[i] for i in data]

['064', '031', '063']

# 가까운 수

In [ ]:
l = [3, 10, 28]

sorted(l, key = lambda x:abs(-20))[0]

3

In [ ]:
def solution(array, n):
    return sorted(array, key = lambda x:(abs(x -n), x -n))[0]

In [ ]:
# [3, 10, 28, 30, 12] => [17, 10, 8, 10, 8]
# [3, 10, 28, 30, 12] => [(17, 3), (10, 10), (8, 28), (10, 30), (8, 12)]
# 원하는 숫자: 20
# result: 28

array = [3, 10, 28, 30, 12]
n = 20

28 - 20 == 8
12 - 20 == -8

20 - 28 == -8
20 - 12 == 8

sorted(array, key=lambda x:(abs(x-n), x))[0]
sorted(array, key=lambda x:(abs(x-n), n-x))[0] # 팁, n-x이거나 x-n 2개 중에 하나입니다.

28

In [ ]:
# i    j    k
# 1    13    1

i = 1
j = 13
k = 1

str(list(range(i, j+1)))
'[1, 2, 3]'.count(str(k))

1

In [ ]:
a = 10
b = 20

# swap

temp = a
a = b
b = temp

# python에서 사용하는 swap

a = 10
b = 20
a, b = b, a
a, b

(20, 10)

In [ ]:
i = 1
j = 13
k = 2

count = 0

for temp in range(i, j):
    count += (str(temp).count(str(k)))

count

0
1
0
0
0
0
0
0
0
0
0
1


In [ ]:
def solution(i, j, k):
    return str(list(range(i, j+1))).count(str(k))

In [ ]:
i = 1
j = 13
k = 1

count = 0
for temp in range(i, j):
    count += str(temp).count(str(k))

count

5

# 직접 출제 문제

In [ ]:
[[0, 5], [3, 5], [7, 10]]
선 = [False] * 10
선

[False, False, False, False, False, False, False, False, False, False]

In [ ]:
for i in range(0, 5 + 1):
    선[i] = True

선

[True, True, True, True, True, True, False, False, False, False]

In [ ]:
for i in range(3, 5):
    선[i] = True

선

[True, True, True, True, True, True, False, False, False, False]

In [ ]:
for i in range(7, 10):
    선[i] = True

선

[True, True, True, True, True, True, False, True, True, True]

In [ ]:
sum(선)

9

In [ ]:
a, b = 10, 10
a = 10;b = 10
a, b

(10, 10)

In [ ]:
# 에라토스테스트의 체 => 소수판별 => 이것을 알고리즘 문제로 내는 것은 저는 반대
소수 = [True] * 120
소수[0] = 소수[1] = False

for i in range(4, 120, 2):
    소수[i] = False

for i in range(6, 120, 3):
    소수[i] = False

# for

소수

[False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [ ]:
16

# 곱해지는 각 자연수중 하나는 무조건
# 제곱근과 같거나 작아야하는거니까

# 4 * 4
# 2 * 8

# 2, 3, 4

# 2, 4, 6, 8, 10, 12
# 3, 6, 9, 12
# ---
# 5, 10, 15

16

In [ ]:
for 소수, 판별 in enumerate(소수):
    if 판별:
        print(소수)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


In [ ]:
# 행렬의 연산과 같은 것은 np를 사용하시면 쉽고 빠르게 풀 수 있습니다.

In [ ]:
# 행렬의 연산과 같은 것은 np를 사용하시면 쉽고 빠르게 풀 수 있습니다.
import numpy as np

x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

In [ ]:
s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
np.where(s == 7)

(array([1]), array([0]))

In [ ]:
# 지뢰찾기
x =[[0, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]]

x = np.array(x)
np.where(x == 1)

(array([0, 1, 2]), array([1, 1, 3]))

In [ ]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

s = 0
for i in x:
    s += i.count(1)

s

3

In [ ]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
x == 1



array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [ ]:
x = [[0, 5, 2, 0],
     [0, 7, 0, 6],
     [0, 1, 3, 5]]

x = np.array(x)
x > 3

array([[False,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True]])